---
title: "Credit Default Risk Insights"
author:  "Harison Gachuru & Sofia Elmi"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r load-libraries, include=FALSE}
library(dplyr)
library(forcats)
library(ggplot2)
library(ggrepel)
library(ggthemes)
library(knitr)
library(readr)
```


```{r config, include=FALSE}
# file paths
DATA_DIR <- file.path("../input/credit-risk")
TRAIN_DATA <- file.path(DATA_DIR, "train.csv")

# global options
knitr::opts_chunk$set(echo = FALSE)
```

```{r load-data, message=FALSE}
col_types <- cols(
  loan_status = col_factor()
)
df <- read_csv(TRAIN_DATA, col_types = col_types)
```

```{r update-columns}
df <- df %>%
  mutate(
    loan_status = fct_recode(loan_status, "Non Default" = "0", "Default" = "1")
  )
```

## Loan status
```{r loan-status, warning=FALSE}
ggplot(data = df, mapping = aes(x = loan_status, fill = loan_status)) +
  geom_bar(mapping = aes(y = after_stat(count)/sum(after_stat(count)))) +
  scale_y_continuous(labels = scales::percent) +
  labs(
    title = "Distribution of loan status",
    x = "Loan status",
    y = "Frequency"
  ) +
  theme_economist() +
  guides(fill = FALSE) 
```

## Interest rate
```{r loan-interest-rate, warning=FALSE}
ggplot(data = df, mapping = aes(x = loan_int_rate, fill = loan_status)) +
  geom_histogram(
    alpha = 0.2,
    position = "identity",
    mapping = aes(color = loan_status),
    bins = 50
  ) +
  labs(
    title = "Distribution of loan interest rate by loan status",
    x = "Interest rate"
  ) +
  theme_economist()
```

## Loan-income ratio
```{r loan-income-ratio}
ggplot(data = df, mapping = aes(x = loan_percent_income, fill = loan_status)) +
  geom_density(alpha = 0.5) +
  labs(
    title = "Distribution of loan-income ratio by loan status",
    x = "Loan-income ratio"
  ) +
  theme_economist()
```

## Loan grade
```{r loan-grade, message=FALSE}
df %>% 
  group_by(loan_grade, loan_status) %>% 
  summarize(n = n()) %>%
  ggplot(mapping = aes(x = loan_grade, y = n, fill = loan_status)) +
    geom_col(position = "dodge") +
    labs(
      title = "Distribution of loan grade by loan status",
      x = "Loan grade"
    ) +
    theme_economist() +
    geom_label_repel(aes(label = n)) + ylab("Frequency")
```

## Home ownership
```{r home-ownership, message=FALSE}
df %>% 
  group_by(loan_status, person_home_ownership ) %>%
  summarise(n = n()) %>%
  ggplot(
    mapping = aes(
      x = reorder(person_home_ownership, -n),
      y = n,
      fill = loan_status )
    ) +
  geom_col(position = 'dodge') +
  geom_label_repel(aes(label = n)) +
  labs(
    title = "Distribution of home ownership by loan status",
    x = "Home ownership",
    y = "Frequency"
  ) +
  theme_economist()
```
